spring.application.name=agenta-backend
server.port=8080

# Local MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/agenta
spring.data.mongodb.connect-timeout=5000
spring.data.mongodb.socket-timeout=5000


# Debugging logs
logging.level.org.springframework.data.mongodb=DEBUG

# Security (For Testing)
spring.security.user.password=ashok123

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agenda.creator.privatelimited@gmail.com
spring.mail.password=yqthzzbbxysytdei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

